production:
  test: something
  
  doctrine:
    proxyDir: ROOT_PATH/app/tmp
    proxyNamespace: Proxies
    
    hydratorDir: ROOT_PATH/app/tmp
    hydratorNamespace: Hydrators
    
    annotationNamespace: Doctrine\ODM\MongoDB\Mapping\
    metadataDriverPath: LIB_PATH/Game/Documents
    
    odm:
      proxyDir: ROOT_PATH/app/tmp
      hydratorDir: ROOT_PATH/app/tmp
      hydratorNamespace: Hydrators
      annotationNamespace: Doctrine\ODM\MongoDB\Mapping\
      metadataDriverPath: LIB_PATH/Game/Documents
      host: localhost
    
      
  frontController:
    controllerNamespace: App\Controller
  
  
development:
  inherit: production
  
  test2: more
  test: override
  
  
  
  
default:
  test: whatever
  
  site:
    name: phpC4
    staticUrl: "/static"
  
  templateEngine: twig
  
  twig:
    templateDir: APP_PATH/App/View
    cache: false
    debug: false
    charset: utf-8
    baseTemplateClass: Twig_Template
    strictVarialbes: false
    autoescape: true
    
  
  smarty:
    templateDir: ROOT_PATH/app/templates
    compileDir: ROOT_PATH/app/tmp/templates_c
    cacheDir: ROOT_PATH/tmp
    configDir: ROOT_PATH/config
    resources:
      c4: C4\View\Template\SmartyExtensions
    defaultResource: c4
    
    
  layout:
    default: layouts/default