#orm:
#  class: C4\Service\DoctrineService
#  
#  properties:
#    proxyDir: $doctrine.proxyDir$
#    proxyNamespace: $doctrine.proxyNamespace$
#    metadataDriverPath: $doctrine.metadataDriverPath$
#    cacheClass: $doctrine.cacheClass$
#    autoGenerateProxies: $doctrine.autoGenerateProxies$
#    
#    connectionOptions:
    

odm:
  class: C4\Service\MongoService
    
  properties:
    host: $doctrine.odm.host$
    proxyDir: $doctrine.odm.proxyDir$
    hydratorDir: $doctrine.odm.hydratorDir$
    hydratorNamespace: $doctrine.odm.hydratorNamespace$
    defaultAnnotationNamespace: $doctrine.odm.annotationNamespace$
    metadataDriverPath: $doctrine.odm.metadataDriverPath$
    defaultDb: $doctrine.odm.db$

     